const reduced=matchMedia('(prefers-reduced-motion: reduce)'),desktop=matchMedia('(min-width: 761px)');
const menu=document.querySelector('.mobile-toggle'),nav=document.querySelector('#mobile-nav');
function closeMenu(){nav.hidden=true;menu.setAttribute('aria-expanded','false');menu.innerHTML='Menu <span aria-hidden="true">+</span>'}
menu.addEventListener('click',()=>{const open=nav.hidden;nav.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.innerHTML=open?'Zamknij <span aria-hidden="true">−</span>':'Menu <span aria-hidden="true">+</span>'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
if(!reduced.matches&&'IntersectionObserver' in window){document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.setProperty('--reveal-delay',(i%3)*70+'ms');observer.observe(el)})}
const chapters=[...document.querySelectorAll('.chapter')],stackCandidates=[...document.querySelectorAll('.chapter-hero,.chapter-about,.chapter-offer,.chapter-blog,.chapter-contact')];
const work=document.querySelector('.chapter-work'),stage=work.querySelector('.work-stage'),rail=work.querySelector('.work-rail'),windowEl=work.querySelector('.work-window'),progress=work.querySelector('.work-progress'),counter=work.querySelector('.work-counter');let travel=0,head=84,ticking=false;
function measure(){head=document.querySelector('.site-header').offsetHeight;const motion=desktop.matches&&!reduced.matches;document.documentElement.classList.toggle('is-static',reduced.matches);stackCandidates.forEach(c=>{c.classList.remove('is-stacked');const fits=c.firstElementChild.scrollHeight<=innerHeight-head+2;c.classList.toggle('is-stacked',motion&&fits)});work.classList.toggle('is-horizontal',motion);travel=motion?Math.max(0,rail.scrollWidth-windowEl.clientWidth+parseFloat(getComputedStyle(windowEl).paddingRight)):0;if(travel<2)travel=0;work.style.setProperty('--travel',travel+'px');requestTick()}
function update(){ticking=false;const vh=innerHeight;let active='';for(const c of chapters){const rect=c.getBoundingClientRect();if(rect.top<vh*.48&&document.querySelector('[data-nav="'+c.dataset.chapter+'"]'))active=c.dataset.chapter;const next=c.nextElementSibling;if(next){const nextTop=next.getBoundingClientRect().top;const out=Math.max(0,Math.min(1,(vh-nextTop)/(vh-head)));c.style.setProperty('--panel-scale',String(1-.028*out));c.style.setProperty('--panel-opacity',String(1-.28*out))}}document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('is-active',a.dataset.nav===active));const total=document.documentElement.scrollHeight-vh;document.querySelector('.site-header').style.setProperty('--page-progress',total>0?String(scrollY/total):'0');if(work.classList.contains('is-horizontal')){const x=Math.max(0,Math.min(travel,head-work.getBoundingClientRect().top));rail.style.setProperty('--rail-x',x+'px');const p=travel?x/travel:0;work.style.setProperty('--work-progress',String(.15+.85*p));const cards=[...rail.querySelectorAll('.work-card:not([hidden])')];const index=Math.min(cards.length,Math.floor(p*Math.max(0,cards.length-1))+1);counter.textContent=String(index).padStart(2,'0')+' / '+String(cards.length).padStart(2,'0')}else rail.style.setProperty('--rail-x','0px')}
function requestTick(){if(!ticking){ticking=true;requestAnimationFrame(update)}}addEventListener('scroll',requestTick,{passive:true});addEventListener('resize',measure,{passive:true});addEventListener('load',measure);desktop.addEventListener('change',measure);reduced.addEventListener('change',()=>{if(reduced.matches)document.querySelectorAll('.reveal').forEach(e=>e.classList.add('is-visible'));measure()});document.fonts.ready.then(measure);
document.querySelectorAll('.area').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)document.querySelectorAll('.area').forEach(other=>{if(other!==item)other.open=false});measure()}));document.querySelectorAll('.faq-list details').forEach(d=>d.addEventListener('toggle',measure));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;rail.querySelectorAll('.work-card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&!card.dataset.category.split(' ').includes(button.dataset.filter);if(!card.hidden)count++});document.querySelector('#filter-status').textContent=`Widoczne realizacje: ${count}`;measure();if(desktop.matches)work.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});else windowEl.scrollTo({left:0,behavior:'instant'})}));
rail.querySelectorAll('.project-button').forEach(button=>button.addEventListener('focus',()=>{if(work.classList.contains('is-horizontal')&&button.matches(':focus-visible')){const card=button.closest('.work-card');const x=Math.min(travel,Math.max(0,card.offsetLeft));const top=scrollY+work.getBoundingClientRect().top-head;window.scrollTo({top:top+x,behavior:'smooth'})}}));
const dialog=document.querySelector('#project-dialog'),close=document.querySelector('.dialog-close');let dataPromise;function getProjects(){return dataPromise??=fetch('./projects-data.json').then(r=>{if(!r.ok)throw new Error('Nie udało się pobrać realizacji');return r.json()})}
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',async()=>{try{const projects=await getProjects(),p=projects[Number(button.dataset.project)];document.querySelector('#dialog-title').textContent=p.name;document.querySelector('#dialog-label').textContent=p.label;document.querySelector('#dialog-description').textContent=p.desc;const gallery=document.querySelector('.dialog-gallery');gallery.replaceChildren(...p.gallery.map((file,i)=>{const img=document.createElement('img');img.src='./assets/'+file;img.alt=p.name+' — przykład realizacji '+(i+1);return img}));dialog.showModal();dialog.scrollTop=0}catch{document.querySelector('#filter-status').textContent='Nie udało się otworzyć realizacji. Spróbuj ponownie.'}}));close.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!nav.hidden){closeMenu();menu.focus()}});measure();


